apiVersion: skaffold/v4beta7
kind: Config
customActions:
- name: render
  containers:
  - name: render
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli@sha256:66e2681aa3099b4e517e4cdcdefff8f2aa45d305007124ccdc09686f6712d018
    command: ['/bin/bash']
    args:
      - '-c'
      - |-
        set -euxo pipefail
        echo $CLOUD_DEPLOY_INPUT_GCS_PATH > manifest.txt
        gcloud storage cp manifest.txt $CLOUD_DEPLOY_OUTPUT_GCS_PATH/manifest.txt
        echo {\"resultStatus\": \"SUCCEEDED\", \"manifestFile\": \"$CLOUD_DEPLOY_OUTPUT_GCS_PATH/manifest.txt\"} > results.json
        gcloud storage cp results.json $CLOUD_DEPLOY_OUTPUT_GCS_PATH/results.json
- name: deploy
  containers:
  - name: deploy
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli@sha256:66e2681aa3099b4e517e4cdcdefff8f2aa45d305007124ccdc09686f6712d018
    command: ['/bin/bash']
    args:
      - '-c'
      - |-
        set -euxo pipefail
        SOURCE_PATH=$(gcloud storage cat $CLOUD_DEPLOY_INPUT_GCS_PATH/manifest.txt)
        gcloud storage cp -R $SOURCE_PATH build.tar.gz
        tar xzvf build.tar.gz
        gcloud storage rsync ./build ${gcs} --recursive --delete-unmatched-destination-objects
        echo {\"resultStatus\": \"SUCCEEDED\"} > results.json
        gcloud storage cp results.json $CLOUD_DEPLOY_OUTPUT_GCS_PATH/results.json
